require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/.pnpm/@capacitor+ios@5.3.0_@capacitor+core@5.3.0/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/.pnpm/@capacitor+ios@5.3.0_@capacitor+core@5.3.0/node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../node_modules/.pnpm/@capacitor+app@5.0.0_@capacitor+core@5.3.0/node_modules/@capacitor/app'
  pod 'CapacitorDevice', :path => '../../node_modules/.pnpm/@capacitor+device@5.0.6_@capacitor+core@5.3.0/node_modules/@capacitor/device'
  pod 'CapacitorNetwork', :path => '../../node_modules/.pnpm/@capacitor+network@5.0.6_@capacitor+core@5.3.0/node_modules/@capacitor/network'
  pod 'TachibanaShinCapacitorFilesystem', :path => '../../node_modules/.pnpm/@tachibana-shin+capacitor-filesystem@5.0.2_@capacitor+core@5.3.0/node_modules/@tachibana-shin/capacitor-filesystem'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
